### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by liamxg** [abschneider/paper-chikungunya-phylogeny#1]
how to install hashmap package, thanks.
I am super interested about your research, and hope you can help me out, thank.

**Comment by LiXingguangBrandonStark** [comment]
rateextract(logfile,burninpercentage,locations,traitname)
[1] "Loading data..."
[1] "Removing burn-in..."
[1] "Creating empty matrix..."
[1] "Extracting rates and indicators from logfile..."
 Error: Must rename columns with a valid subscript vector.
x Subscript has the wrong type `xfun_raw_string`.
ℹ It must be numeric or character.
Run `rlang::last_error()` to see where the error occurred.

**Comment by mtw** [comment]
Hello @LiXingguangBrandonStark,
I would say `install.packages("hashmap")` should do it.
Cheers,
Michael

**Comment by liamxg** [comment]
install.packages("hashmap")
Warning in install.packages :
  package ‘hashmap’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by liamxg** [comment]
not available

**Comment by mtw** [comment]
OK just realized that the hashmap package has been removed from CRAN (see https://cran.r-project.org/web/packages/hashmap/index.html). 
@abschneider can you recommend an alternative?

**Comment by abschneider** [comment]
"Package ‘hashmap’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2020-03-17 as check problems were not corrected despite reminders."

You may access and install the R package from archive here: https://cran.r-project.org/src/contrib/Archive/hashmap/

**Comment by BEAST-Community** [comment]
@mtw @abschneider thanks for telling me this, this is very important to me.

**Comment by liamxg** [comment]
@mtw @abschneider thanks for telling me this, this is very important to me.
